### ISSUE TITLE
Websocket command entity/source is changed in Home Assistant Core 2023.10

### ISSUE THREAD

**Issue by emontnemery** [vicfergar/HassClient#12]
Websocket command entity/source is changed in Home Assistant Core 2023.10, and now provides much less information

Reference: https://developers.home-assistant.io/blog/2023/09/12/ws-entity-source-simplified

**Comment by vicfergar** [comment]
Thanks for the heads up @emontnemery, I will update the existing models to be aligned with the latest version.

**Comment by vicfergar** [comment]
Fixed in #16
