### ISSUE TITLE
Fire an Event

### ISSUE THREAD

**Issue by shaonianzhentan** [vicfergar/HassClient#7]
Again thanks for HassClient
This project is great and has helped me a lot
But I didn't find a way to trigger the event

**Comment by vicfergar** [comment]
Hi @shaonianzhentan,

I'm not sure about what is the issue you are reporting. This library allows you to consume events from the Hass instance server using WS communication. The way you can consume these events is on the Readme: https://github.com/vicfergar/HassClient#event-subscription

**Comment by shaonianzhentan** [comment]
Thank you for your reply
I customized an event and I want to trigger it instead of subscribing to it

**Comment by vicfergar** [comment]
Ok, I didn't notice that they have included an fire_event command in the WS API. Currently there is no specific methods to fire events in the API, but you can do it using raw commands feature: https://github.com/vicfergar/HassClient#raw-commands

Check WebSocket API docs from HASS to see how the command should contains: https://developers.home-assistant.io/docs/api/websocket#fire-an-event

**Comment by shaonianzhentan** [comment]
I look forward to you adding this feature，Thanks again

**Comment by vicfergar** [comment]
I have integrated fire event feature in the branch https://github.com/vicfergar/HassClient/tree/feature/update_ws_api
